//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingResources.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class French {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal French() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsingResources.Properties.French", typeof(French).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effacer.
        /// </summary>
        internal static string BUTTON_FILTERS_CLEAR {
            get {
                return ResourceManager.GetString("BUTTON_FILTERS_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        internal static string BUTTON_FILTERS_SEARCH {
            get {
                return ResourceManager.GetString("BUTTON_FILTERS_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string BUTTON_NO {
            get {
                return ResourceManager.GetString("BUTTON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string BUTTON_YES {
            get {
                return ResourceManager.GetString("BUTTON_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change.
        /// </summary>
        internal static string CHANGETRACKING_CHANGE {
            get {
                return ResourceManager.GetString("CHANGETRACKING_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur ayant fait la création.
        /// </summary>
        internal static string CHANGETRACKING_CREATEDBY {
            get {
                return ResourceManager.GetString("CHANGETRACKING_CREATEDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de création.
        /// </summary>
        internal static string CHANGETRACKING_CREATIONDATE {
            get {
                return ResourceManager.GetString("CHANGETRACKING_CREATIONDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Deleted.
        /// </summary>
        internal static string CHANGETRACKING_DATEDELETED {
            get {
                return ResourceManager.GetString("CHANGETRACKING_DATEDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted By.
        /// </summary>
        internal static string CHANGETRACKING_DELETEDBY {
            get {
                return ResourceManager.GetString("CHANGETRACKING_DELETEDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        internal static string CHANGETRACKING_HISTORY {
            get {
                return ResourceManager.GetString("CHANGETRACKING_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is Deleted.
        /// </summary>
        internal static string CHANGETRACKING_IS_DELETED {
            get {
                return ResourceManager.GetString("CHANGETRACKING_IS_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur ayant fait la dernière modification.
        /// </summary>
        internal static string CHANGETRACKING_LASTMODIFIEDBY {
            get {
                return ResourceManager.GetString("CHANGETRACKING_LASTMODIFIEDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de dernière modification.
        /// </summary>
        internal static string CHANGETRACKING_LASTMODIFIEDDATE {
            get {
                return ResourceManager.GetString("CHANGETRACKING_LASTMODIFIEDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When.
        /// </summary>
        internal static string CHANGETRACKING_REVISION_DATE {
            get {
                return ResourceManager.GetString("CHANGETRACKING_REVISION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transaction In Progress.
        /// </summary>
        internal static string CHANGETRACKING_REVISION_TRANSACTION_IN_PROGRESS {
            get {
                return ResourceManager.GetString("CHANGETRACKING_REVISION_TRANSACTION_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who.
        /// </summary>
        internal static string CHANGETRACKING_REVISION_USER {
            get {
                return ResourceManager.GetString("CHANGETRACKING_REVISION_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revision Created.
        /// </summary>
        internal static string CHANGETRACKING_REVISIONCREATED {
            get {
                return ResourceManager.GetString("CHANGETRACKING_REVISIONCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revision Deleted.
        /// </summary>
        internal static string CHANGETRACKING_REVISIONDELETED {
            get {
                return ResourceManager.GetString("CHANGETRACKING_REVISIONDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revision Last Modified.
        /// </summary>
        internal static string CHANGETRACKING_REVISIONLASTMODIFIED {
            get {
                return ResourceManager.GetString("CHANGETRACKING_REVISIONLASTMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag Date.
        /// </summary>
        internal static string CHANGETRACKING_TAG_DATE {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string CHANGETRACKING_TAG_DESCRIPTION {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System ?.
        /// </summary>
        internal static string CHANGETRACKING_TAG_ISSYSTEM {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAG_ISSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag Label.
        /// </summary>
        internal static string CHANGETRACKING_TAG_LABEL {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary.
        /// </summary>
        internal static string CHANGETRACKING_TAG_SUMMARY {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAG_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string CHANGETRACKING_TAG_VERSION {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAG_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tagged By.
        /// </summary>
        internal static string CHANGETRACKING_TAGGED_BY {
            get {
                return ResourceManager.GetString("CHANGETRACKING_TAGGED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string COMMAND_CANCEL {
            get {
                return ResourceManager.GetString("COMMAND_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string COMMAND_DELETE {
            get {
                return ResourceManager.GetString("COMMAND_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string COMMAND_EDIT {
            get {
                return ResourceManager.GetString("COMMAND_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string COMMAND_MODIFY {
            get {
                return ResourceManager.GetString("COMMAND_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string COMMAND_NEW {
            get {
                return ResourceManager.GetString("COMMAND_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        internal static string COMMAND_SAVE {
            get {
                return ResourceManager.GetString("COMMAND_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        internal static string COMMAND_VIEW {
            get {
                return ResourceManager.GetString("COMMAND_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr(e) de vouloir supprimer cet élément ?.
        /// </summary>
        internal static string CONFIRM_DELETE_BODY {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de suppression.
        /// </summary>
        internal static string CONFIRM_DELETE_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquer pour ajouter....
        /// </summary>
        internal static string DROPDOWN_MENU_ADD_ITEM {
            get {
                return ResourceManager.GetString("DROPDOWN_MENU_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun résultat.
        /// </summary>
        internal static string DROPDOWN_MENU_NO_MATCH {
            get {
                return ResourceManager.GetString("DROPDOWN_MENU_NO_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune donnée.
        /// </summary>
        internal static string DROPDOWN_NO_DATA {
            get {
                return ResourceManager.GetString("DROPDOWN_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -.
        /// </summary>
        internal static string ENUM_UNDEFINED_VALUE {
            get {
                return ResourceManager.GetString("ENUM_UNDEFINED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur au chargement de la page. Veuillez contacter un administrateur..
        /// </summary>
        internal static string ERROR_GENERIC_POPUP_BODY {
            get {
                return ResourceManager.GetString("ERROR_GENERIC_POPUP_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string ERROR_GENERIC_POPUP_TITLE {
            get {
                return ResourceManager.GetString("ERROR_GENERIC_POPUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur au chargement de la page. Veuillez contacter un administrateur..
        /// </summary>
        internal static string ERROR_LOADING_PAGE {
            get {
                return ResourceManager.GetString("ERROR_LOADING_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à l&apos;appel de %OPERATION%.
        /// </summary>
        internal static string ERROR_ON_COMPONENTCALL {
            get {
                return ResourceManager.GetString("ERROR_ON_COMPONENTCALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du comptage des éléments.
        /// </summary>
        internal static string ERROR_ON_COUNT {
            get {
                return ResourceManager.GetString("ERROR_ON_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la suppression de l&apos;élément.
        /// </summary>
        internal static string ERROR_ON_DELETE {
            get {
                return ResourceManager.GetString("ERROR_ON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du chargement de l&apos;élément.
        /// </summary>
        internal static string ERROR_ON_GET {
            get {
                return ResourceManager.GetString("ERROR_ON_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du chargement de la collection des éléments.
        /// </summary>
        internal static string ERROR_ON_GETCOLLECTION {
            get {
                return ResourceManager.GetString("ERROR_ON_GETCOLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la sauvegarde de l&apos;élément.
        /// </summary>
        internal static string ERROR_ON_SAVE {
            get {
                return ResourceManager.GetString("ERROR_ON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléchargement du fichier %FILENAME% échoué.
        /// </summary>
        internal static string ERROR_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("ERROR_UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string FORM_COMMAND_MODIFY {
            get {
                return ResourceManager.GetString("FORM_COMMAND_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        internal static string FORM_COMMAND_NEW {
            get {
                return ResourceManager.GetString("FORM_COMMAND_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        internal static string GRID_COMMAND_MODIFY {
            get {
                return ResourceManager.GetString("GRID_COMMAND_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string GRID_COMMAND_NEW {
            get {
                return ResourceManager.GetString("GRID_COMMAND_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data.
        /// </summary>
        internal static string IMPORTEXPORT_DATA {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string IMPORTEXPORT_DATE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date fin.
        /// </summary>
        internal static string IMPORTEXPORT_DATE_END {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_DATE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début.
        /// </summary>
        internal static string IMPORTEXPORT_DATE_START {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_DATE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        internal static string IMPORTEXPORT_DETAILS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé.
        /// </summary>
        internal static string IMPORTEXPORT_DONE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin.
        /// </summary>
        internal static string IMPORTEXPORT_END {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string IMPORTEXPORT_ERROR {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur ignorée.
        /// </summary>
        internal static string IMPORTEXPORT_ERROR_IGNORED {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_ERROR_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune donnée.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORT_EMPTYFORM {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORT_EMPTYFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail d&apos;export : aucune donnée.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORT_EMPTYGRID {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORT_EMPTYGRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails d&apos;export .
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTDETAILS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier exporté.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTED_FILE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille du fichier exporté (kb).
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTED_FILESIZE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTED_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du travail d&apos;export.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTJOBDETAILS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTJOBDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;export.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTJOBNAME {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTJOBNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux d&apos;export.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTJOBS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTJOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs d&apos;export.
        /// </summary>
        internal static string IMPORTEXPORT_EXPORTLOGS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_EXPORTLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec.
        /// </summary>
        internal static string IMPORTEXPORT_FAILED {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune donnée.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORT_EMPTYFORM {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORT_EMPTYFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail d&apos;import : aucune donnée.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORT_EMPTYGRID {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORT_EMPTYGRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORT_NAME {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTDETAILS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier importé.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTED_FILE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille du fichier importé (kb).
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTED_FILESIZE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTED_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du travail d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTJOBDETAILS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTJOBDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des imports.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTJOBLIST {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTJOBLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTJOBS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTJOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du log d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTLOGDETAILS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTLOGDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTLOGS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun log d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_IMPORTLOGS_EMPTY {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IMPORTLOGS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cours.
        /// </summary>
        internal static string IMPORTEXPORT_IN_PROGRESS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string IMPORTEXPORT_INFORMATION {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail d&apos;import.
        /// </summary>
        internal static string IMPORTEXPORT_JOB_NAME {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_JOB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;export.
        /// </summary>
        internal static string IMPORTEXPORT_LABEL_EXPORT_NAME {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_LABEL_EXPORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de ligne.
        /// </summary>
        internal static string IMPORTEXPORT_LINE_NUMBER {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_LINE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log.
        /// </summary>
        internal static string IMPORTEXPORT_LOG {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun log.
        /// </summary>
        internal static string IMPORTEXPORT_LOG_EMPTY {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_LOG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        internal static string IMPORTEXPORT_LOGS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de Log.
        /// </summary>
        internal static string IMPORTEXPORT_LOGTYPE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_LOGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pourcentage d&apos;avancement.
        /// </summary>
        internal static string IMPORTEXPORT_PERCENT_COMPLETE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_PERCENT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progrès.
        /// </summary>
        internal static string IMPORTEXPORT_PROGRESS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignoré.
        /// </summary>
        internal static string IMPORTEXPORT_SKIPPED {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_SKIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Début.
        /// </summary>
        internal static string IMPORTEXPORT_START {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Débuté.
        /// </summary>
        internal static string IMPORTEXPORT_STARTED {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        internal static string IMPORTEXPORT_STATUS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite.
        /// </summary>
        internal static string IMPORTEXPORT_SUCCEEDED {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite avec erreurs.
        /// </summary>
        internal static string IMPORTEXPORT_SUCCEEDED_WITH_ERRORS {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_SUCCEEDED_WITH_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string IMPORTEXPORT_TYPE {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention.
        /// </summary>
        internal static string IMPORTEXPORT_WARNING {
            get {
                return ResourceManager.GetString("IMPORTEXPORT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : Aucune donnée.
        /// </summary>
        internal static string INFO_FORM_EMPTY {
            get {
                return ResourceManager.GetString("INFO_FORM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Généré automatiquement {1} pour l&apos;entité &apos;{0}&apos;.
        /// </summary>
        internal static string INFO_GENERATED_IMPORT_SECTION {
            get {
                return ResourceManager.GetString("INFO_GENERATED_IMPORT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : Aucune donnée.
        /// </summary>
        internal static string INFO_GRID_EMPTY {
            get {
                return ResourceManager.GetString("INFO_GRID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement en cours....
        /// </summary>
        internal static string INFO_LOADING_DATA_WAIT {
            get {
                return ResourceManager.GetString("INFO_LOADING_DATA_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page en cours de chargement. Veuillez patienter....
        /// </summary>
        internal static string INFO_LOADING_PAGE_WAIT {
            get {
                return ResourceManager.GetString("INFO_LOADING_PAGE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement du fichier %FILENAME%.
        /// </summary>
        internal static string INFO_UPLOAD_IN_PROGRESS {
            get {
                return ResourceManager.GetString("INFO_UPLOAD_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ficher %FILENAME% téléchargé avec succès..
        /// </summary>
        internal static string INFO_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("INFO_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de charger le fichier. La taille maximale autorisée est de %SIZE% ko.
        /// </summary>
        internal static string INFO_UPLOAD_TOO_LARGE {
            get {
                return ResourceManager.GetString("INFO_UPLOAD_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  : .
        /// </summary>
        internal static string LABEL_COLON {
            get {
                return ResourceManager.GetString("LABEL_COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page {0} : Détails.
        /// </summary>
        internal static string LABEL_DETAILS_PAGE {
            get {
                return ResourceManager.GetString("LABEL_DETAILS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre.
        /// </summary>
        internal static string LABEL_FILTER {
            get {
                return ResourceManager.GetString("LABEL_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  : Détails.
        /// </summary>
        internal static string LABEL_FORM_DETAILS_APPENDAGE {
            get {
                return ResourceManager.GetString("LABEL_FORM_DETAILS_APPENDAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synthèse.
        /// </summary>
        internal static string LABEL_FORM_TAB_MAIN {
            get {
                return ResourceManager.GetString("LABEL_FORM_TAB_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à $PLURALIZE.
        /// </summary>
        internal static string LABEL_GRID_COLLECTION_APPENDAGE {
            get {
                return ResourceManager.GetString("LABEL_GRID_COLLECTION_APPENDAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eléments : .
        /// </summary>
        internal static string LABEL_GRID_ITEM_COUNT {
            get {
                return ResourceManager.GetString("LABEL_GRID_ITEM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page {0}.
        /// </summary>
        internal static string LABEL_ITEMS_PAGE {
            get {
                return ResourceManager.GetString("LABEL_ITEMS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page.
        /// </summary>
        internal static string LABEL_PAGE {
            get {
                return ResourceManager.GetString("LABEL_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à $PLURALIZE.
        /// </summary>
        internal static string LABEL_RELATION_MANYSIDEAPPENDAGE {
            get {
                return ResourceManager.GetString("LABEL_RELATION_MANYSIDEAPPENDAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autorisation.
        /// </summary>
        internal static string MEMBERSHIP_AUTHORIZATION {
            get {
                return ResourceManager.GetString("MEMBERSHIP_AUTHORIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérification de votre accès: une erreur est survenue..
        /// </summary>
        internal static string MEMBERSHIP_AUTHORIZATION_ERROR {
            get {
                return ResourceManager.GetString("MEMBERSHIP_AUTHORIZATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer le mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changement mot de passe en cours ....
        /// </summary>
        internal static string MEMBERSHIP_CHANGING_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CHANGING_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation du mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion en cours....
        /// </summary>
        internal static string MEMBERSHIP_CONNECTING {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string MEMBERSHIP_CONNECTION {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe actuel.
        /// </summary>
        internal static string MEMBERSHIP_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe actuel incorrect..
        /// </summary>
        internal static string MEMBERSHIP_CURRENT_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("MEMBERSHIP_CURRENT_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse email.
        /// </summary>
        internal static string MEMBERSHIP_EMAIL {
            get {
                return ResourceManager.GetString("MEMBERSHIP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse email fournie est incorrecte..
        /// </summary>
        internal static string MEMBERSHIP_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("MEMBERSHIP_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse email obligatoire.
        /// </summary>
        internal static string MEMBERSHIP_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de changer le mot de passe..
        /// </summary>
        internal static string MEMBERSHIP_ERROR_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_ERROR_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de renvoyer les informations de récupération de mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_FAILED_SEND_RECOVERY_INFO {
            get {
                return ResourceManager.GetString("MEMBERSHIP_FAILED_SEND_RECOVERY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        internal static string MEMBERSHIP_IDENTIFICATION {
            get {
                return ResourceManager.GetString("MEMBERSHIP_IDENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez été déconnecté suite à inactivité. Merci de rentrer à nouveau vos identifiants pour continuer..
        /// </summary>
        internal static string MEMBERSHIP_INFO_INACTIVITY_LOGOUT {
            get {
                return ResourceManager.GetString("MEMBERSHIP_INFO_INACTIVITY_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suite à inactivité prolongée vous allez être déconnecté(e) prochainement. Cliquer pour maintenir votre session active..
        /// </summary>
        internal static string MEMBERSHIP_INFO_INACTIVITY_LOGOUT_PENDING {
            get {
                return ResourceManager.GetString("MEMBERSHIP_INFO_INACTIVITY_LOGOUT_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant obligatoire.
        /// </summary>
        internal static string MEMBERSHIP_INFO_USERNAME_REQUIRED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_INFO_USERNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string MEMBERSHIP_LOGIN {
            get {
                return ResourceManager.GetString("MEMBERSHIP_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string MEMBERSHIP_LOGIN_LINK {
            get {
                return ResourceManager.GetString("MEMBERSHIP_LOGIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant ou mot de passe inconnus..
        /// </summary>
        internal static string MEMBERSHIP_LOGIN_UNKNOWN {
            get {
                return ResourceManager.GetString("MEMBERSHIP_LOGIN_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string MEMBERSHIP_LOGMOTE_CONNECTION {
            get {
                return ResourceManager.GetString("MEMBERSHIP_LOGMOTE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string MEMBERSHIP_LOGOUT_LINK {
            get {
                return ResourceManager.GetString("MEMBERSHIP_LOGOUT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe perdu ?.
        /// </summary>
        internal static string MEMBERSHIP_LOST_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_LOST_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : la demande à été annullée suite à droits inssufisants..
        /// </summary>
        internal static string MEMBERSHIP_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe a expiré. Veuillez changer de mot de passe..
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD_EXPIRED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe incorrect..
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs &apos;Nouveau mot de passe&apos; et &apos;Confirmation du mot de passe&apos; doivent être identiques..
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD_MISMATCH {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les mots de passe ne doivent pas être identiques.
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD_MUST_BE_DIFFERENT {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD_MUST_BE_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe n&apos;est pas valide .
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD_REJECTED_DUE_TO_POLICY {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD_REJECTED_DUE_TO_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe obligatoire.
        /// </summary>
        internal static string MEMBERSHIP_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Droit d&apos;accès refusé..
        /// </summary>
        internal static string MEMBERSHIP_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        internal static string MEMBERSHIP_REGISTER {
            get {
                return ResourceManager.GetString("MEMBERSHIP_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de l&apos;enregistrement : le format de l&apos;email n&apos;est pas valide.
        /// </summary>
        internal static string MEMBERSHIP_REGISTER_ERROR_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_REGISTER_ERROR_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription en cours ....
        /// </summary>
        internal static string MEMBERSHIP_REGISTERING {
            get {
                return ResourceManager.GetString("MEMBERSHIP_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rester connecté.
        /// </summary>
        internal static string MEMBERSHIP_REMEMBER_ME {
            get {
                return ResourceManager.GetString("MEMBERSHIP_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;entrer vos identifiants pour continuer..
        /// </summary>
        internal static string MEMBERSHIP_REQUEST_CREDENTIALS {
            get {
                return ResourceManager.GetString("MEMBERSHIP_REQUEST_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;entrer à nouveau vos identifiants pour continuer..
        /// </summary>
        internal static string MEMBERSHIP_REREQUEST_CREDENTIALS {
            get {
                return ResourceManager.GetString("MEMBERSHIP_REREQUEST_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialisation du mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de réinitialiser le mot de passe.
        /// </summary>
        internal static string MEMBERSHIP_RESET_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_RESET_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La demande de réinitialisation de mot de passe a expiré.
        /// </summary>
        internal static string MEMBERSHIP_RESET_PASSWORD_REQUEST_EXPIRED {
            get {
                return ResourceManager.GetString("MEMBERSHIP_RESET_PASSWORD_REQUEST_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialisation du mot de passe en cours....
        /// </summary>
        internal static string MEMBERSHIP_RESETTING_PASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSHIP_RESETTING_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant.
        /// </summary>
        internal static string MEMBERSHIP_USERNAME {
            get {
                return ResourceManager.GetString("MEMBERSHIP_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom d&apos;utilisateur est déjà pris.
        /// </summary>
        internal static string MEMBERSHIP_USERNAME_ALREADY_TAKEN {
            get {
                return ResourceManager.GetString("MEMBERSHIP_USERNAME_ALREADY_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        internal static string MEMBERSHIP_WELCOME {
            get {
                return ResourceManager.GetString("MEMBERSHIP_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        internal static string NAVIGATION_ADMINISTRATION {
            get {
                return ResourceManager.GetString("NAVIGATION_ADMINISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        internal static string NAVIGATION_HOME {
            get {
                return ResourceManager.GetString("NAVIGATION_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string NAVIGATION_IMPORTEXPORT_EXPORT {
            get {
                return ResourceManager.GetString("NAVIGATION_IMPORTEXPORT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string NAVIGATION_IMPORTEXPORT_IMPORT {
            get {
                return ResourceManager.GetString("NAVIGATION_IMPORTEXPORT_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger le fichier.
        /// </summary>
        internal static string SEARCH_DOWLOAD_LINK {
            get {
                return ResourceManager.GetString("SEARCH_DOWLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champ.
        /// </summary>
        internal static string SEARCH_LABEL_FIELDNAME {
            get {
                return ResourceManager.GetString("SEARCH_LABEL_FIELDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche.
        /// </summary>
        internal static string SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string SEARCH_RESULT_DATA {
            get {
                return ResourceManager.GetString("SEARCH_RESULT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document.
        /// </summary>
        internal static string SEARCH_RESULT_DOCUMENT {
            get {
                return ResourceManager.GetString("SEARCH_RESULT_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les détails.
        /// </summary>
        internal static string SEARCH_VIEW_DETAILS_LINK {
            get {
                return ResourceManager.GetString("SEARCH_VIEW_DETAILS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {image.name} ne doit pas dépasser {maxImageWidth} x {maxImageHeight} (image sélectionnée {image.width} x {image.height}).
        /// </summary>
        internal static string UPLOAD_IMAGE_TOO_LARGE {
            get {
                return ResourceManager.GetString("UPLOAD_IMAGE_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;entité %ENTITYNAME% ne respecte pas la condition : %RULE%.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_CUSTOM_RULE {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_CUSTOM_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ %FIELDNAME% doit être supérieur ou égal à %MIN%.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_GTE {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_GTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ %FIELDNAME% doit contenir &apos;%PATTERN%.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_LIKE {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ %FIELDNAME% doit être inférieur ou égal à %MAX%.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_LTE {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_LTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La taille du champ %FIELDNAME% doit être inférieure à %LENGTH% caractères.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_MAXLENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ %FIELDNAME% doit vérifier l&apos;expression %PATTERN%.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_PATTERN {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ %FIELDNAME% doit être dans l&apos;intervalle [%MIN%, %MAX%].
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_RANGE {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ %FIELDNAME% est obligatoire.
        /// </summary>
        internal static string VALIDATION_RULE_FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_RULE_FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez des changements non sauvegardés. Etes-vous sûr(e) de vouloir quitter la page ?.
        /// </summary>
        internal static string WARNING_UNSAVED_CHANGES {
            get {
                return ResourceManager.GetString("WARNING_UNSAVED_CHANGES", resourceCulture);
            }
        }
    }
}
